sudo: required
services:
  - docker

before_install:
  - docker build -t akash/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true akash/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: us-west-2
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-west-2-243020057751"
  bucket_path: "docker"
  on:
    branch: master 
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECREATE_KEY"

